### PR TITLE
Azure blob in flat folder structure

### PR DESCRIPTION
**Pull request by yogigrantz**
Added an option to output Azure blob in flat folder structure with custom filename prefix

Summary of the changes (Less than 80 chars)
 - Added internal static string to store the custom prefix
 - Added public overload to include the custom name parm
 - Modified existing nested folder creation to accept the flat folder option

Addresses #25885

previous discussion: https://github.com/dotnet/extensions/pull/3391

### CODE REVIEW

**Comment by wtgodbe** [comment]
@JunTaoLuo who owns this package now, since it's moved from Extensions?

**Comment by Pilchie** [comment]
@davidfowl do you know who knows about this package?

**Comment by shirhatti** [comment]
Pavel created the package and no one has touched it since.

**Comment by Pilchie** [comment]
Also tagging @javiercn.

File: src/Logging.AzureAppServices/src/BlobLoggerProvider.cs [hunk 1]
```diff
@@ -58,10 +58,20 @@ public BlobLoggerProvider(IOptionsMonitor<AzureBlobLoggerOptions> options)
         internal override async Task WriteMessagesAsync(IEnumerable<LogMessage> messages, CancellationToken cancellationToken)
         {
             var eventGroups = messages.GroupBy(GetBlobKey);
+            DateTime currDate = DateTime.Now;
             foreach (var eventGroup in eventGroups)
             {
                 var key = eventGroup.Key;
-                var blobName = $"{_appName}/{key.Year}/{key.Month:00}/{key.Day:00}/{key.Hour:00}/{_fileName}";
+                //var blobName = $"{_appName}/{key.Year}/{key.Month:00}/{key.Day:00}/{key.Hour:00}/{_fileName}";
```
Comment (davidfowl) [inline src/Logging.AzureAppServices/src/BlobLoggerProvider.cs:65]: Why is this commented out?

Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs:65]: That code was replaced with the logic from line 66 - 74 because it forces nested folder in Azure blob. Line 71 produces a flat folder structure, while line 74 produces the original nested folder structure where the code was commented out.

Comment (davidfowl) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs:65]: Shouldn't it be removed then? Why did you leave the code in but commented out?

Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs:65]: Yes you're right, it should be removed. I will remove it and commit my change

Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs]: @davidfowl : I removed the commented out code, committed and pushed. This is my first time contributing, and I was not sure whether to leave commented out original code or to delete. But now I know to go ahead and delete when deemed not needed. Thank you.

Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs]: @davidfowl : After removing the commented our code, it would not pass the checks. Could you please advise what might have gone wrong, could this be something on the CI side?

**Comment by wtgodbe** [comment]
We were having some issues with our selenium tests, they should be fixed now. This should pass on retry

**Comment by yogigrantz** [comment]
> Azure Pipelines successfully started running 2 pipeline(s).

still failing? hmmm.... could we try again please?

**Comment by wtgodbe** [comment]
@yogigrantz the CI failures are unrelated, we're having some issues w/ our template tests at the moment. Should hopefully be resolved soon.

**Comment by yogigrantz** [comment]
> @yogigrantz the CI failures are unrelated, we're having some issues w/ our template tests at the moment. Should hopefully be resolved soon.

Thank you William!

**Comment by yogigrantz** [comment]
> /azp run

still failing ... I should have deleted that line in the first place  :(

**Comment by Pilchie** [comment]
Let's give it another shot.

**Comment by Pilchie** [comment]
@davidfowl or @javiercn - can one of you review this?

**Comment by yogigrantz** [comment]
> Let's give it another shot.

All checks have passed now :) Thank you All!

File: src/Logging.AzureAppServices/src/BlobLoggerProvider.cs (hunk 1 above)
Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs]: @davidfowl : The build is ready for your review. Could you please revisit this PR? Thank you!

**Comment by yogigrantz** [comment]
@davidfowl @javiercn @Pilchie @wtgodbe @JunTaoLuo @shirhatti 
Could I please have this pull request approved before the CI automatically closes this issue. This feature is very important to our company to avoid workaround custom/duplicate Extension API. 

I can put sample Azure application in GitHub if that helps?. Please do let me know. Thank you so much, appreciate your time!

**Comment by BrennanConroy** [comment]
@davidfowl Could you take a quick look at this and then we can bring it to API review?

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs [hunk 2]
```diff
@@ -17,6 +17,22 @@ namespace Microsoft.Extensions.Logging
     /// </summary>
     public static class AzureAppServicesLoggerFactoryExtensions
     {
+        internal static string CustomPrefix;
```
Comment (davidfowl) [inline src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:20]: This doesn't work because multiple independent calls in the same assembly will cause this to be overwritten.

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs [hunk 3]
```diff
@@ -17,6 +17,22 @@ namespace Microsoft.Extensions.Logging
...
+        /// <summary>
+        /// 
+        /// </summary>
+        /// <param name="builder"></param>
+        /// <param name="customPrefix"></param>
+        /// <returns></returns>
+        public static ILoggingBuilder AddAzureWebAppDiagnostics(this ILoggingBuilder builder, string customPrefix)
+        {
+            CustomPrefix = customPrefix;
+            var context = WebAppContext.Default;
```
Comment (davidfowl) [inline src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:30]: The custom prefix should be passed into the constructor.

File: src/Logging.AzureAppServices/src/BlobLoggerProvider.cs [hunk 4]
```diff
@@ -58,10 +58,19 @@ public BlobLoggerProvider(IOptionsMonitor<AzureBlobLoggerOptions> options)
...
         {
             var eventGroups = messages.GroupBy(GetBlobKey);
+            DateTime currDate = DateTime.Now;
             foreach (var eventGroup in eventGroups)
             {
                 var key = eventGroup.Key;
-                var blobName = $"{_appName}/{key.Year}/{key.Month:00}/{key.Day:00}/{key.Hour:00}/{_fileName}";
+                string blobName;
+
+                if (!string.IsNullOrEmpty(AzureAppServicesLoggerFactoryExtensions.CustomPrefix))
```
Comment (davidfowl) [inline src/Logging.AzureAppServices/src/BlobLoggerProvider.cs:67]: This shouldn't be looked up via a static, but instead should be an instance.

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs (hunk 3 above)
Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:30]: @davidfowl 
This is inside a static class, where there is no constructor. 

AddAzureWebAppDiagnostics is an overload extension of ILoggingBuilder, which is the "entry point" to this API. The web application program injects this API to the IHost container like this:

 ihost.ConfigureLogging(x =>
            {
                x.AddAzureWebAppDiagnostics(customPrefixName);
            });

as opposed to the original version, where the DI is coded like this:

 ihost.ConfigureLogging(x =>
            {
                x.AddAzureWebAppDiagnostics();
            });

Notice that all I did was adding that customPrefixName option and store its value in a static field where the provider checks whether to use the custom prefixed flat blob filename logic. I didn't want to touch the original method if possible, out of respect to the original programmer. Please let me know if there is a more preferable approach to implement this logic

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs (hunk 2 above)
Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:20]: This assembly is designed to be called only once when the IHostBuilder container is configured in Program.cs of a web application. Please refer to the next comment.

File: src/Logging.AzureAppServices/src/BlobLoggerProvider.cs (hunk 4 above)
Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/BlobLoggerProvider.cs:67]: This entire Azure Blob / File Log API is only called once in the beginning of the program run. I could create a new singleton class that contains this one string, but I believe that would be overkill. Unless that is the preferred approach? Please let me know. 
I have tested this solution in Azure and it works flawlessly both ways. The original way, where the blob is structured under appname/yyyy/mm/dd/hh/appInstanceId_blobname, and the modified way, where the blob is named {customprefix}{yyyy}(mm){dd} .

The only difference in setup is whether or not to pass the customPrefix name

ihost.ConfigureLogging(x =>
{
x.AddAzureWebAppDiagnostics(**customPrefixName**);
});

or

ihost.ConfigureLogging(x =>
{
x.AddAzureWebAppDiagnostics**()**;
});

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs (hunk 2 above)
Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:20]: The concept of Logging Provider is that it is called once throughout the application lifetime. It's either with CustomPrefix or without. And the only place this value is set is at the entry point where the provider is injected to IHostBuilder ConfigureLogging. Nowehere else. Please re-review this change. Thank you. - cc: @BrennanConroy

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs (hunk 3 above)
Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:30]: This is a static class extension entry point to IHostBuilder ConfigureLogging Dependency Injection. It takes the responsibility of a constructor. I'm sure you are familiar with the use of Logging Provider Dependency Injection to IHostBuilder ConfigureLogging. Please revisit this code, I appreciate your time!

Comment (davidfowl) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:30]: We don't design anything like this, statics are pretty much forbidden, especially mutable ones like this. This needs to be a constructor argument to the instance.

**Review by yogigrantz — COMMENTED** [review]
Removed the mutable object and store the customPrefixFilename string in the AzureBlobLoggerOptions

**Comment by yogigrantz** [comment]
@wtgodbe  There are build issue on this module, error RS0016: (NETCORE_ENGINEERING_TELEMETRY=Build) Symbol 'AddAzureWebAppDiagnostics' is not part of the declared API. Could you please help me out? Thank you

**Comment by wtgodbe** [comment]
Looks like we need to update the API baselines since this is adding new API - @dougbu could you remind me how to do that?

**Comment by dougbu** [comment]
> @dougbu could you remind me how to do that?

I strongly recommend **not** trying to change the PublicAPI.Unshipped.txt files manually. The analyzer has fairly nice fixers that work only in Visual Studio. So,
1. Open a (preferably small) `*.slnf` file containing the project with API changes in VS
2. Build the solution
3. Click on one of the errors
4. Use the light bulb 💡 or right click to fix the error _globally_. I say _globally_ because it's a pain to click on every error and fix it individually
5. For errors at a lower level than added, changed, or removed surface area, you may need to either fix the API or suppress the error e.g. https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/EventCallbackFactoryBinderExtensions.cs#L35

**Comment by dougbu** [comment]
Oh, it may be necessary to repeat the above in VS because the first round didn't get far enough to hit all of the `public` API issues

File: src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs [hunk 5]
```diff
@@ -21,15 +21,17 @@ public static class AzureAppServicesLoggerFactoryExtensions
         /// Adds an Azure Web Apps diagnostics logger.
         /// </summary>
         /// <param name="builder">The extension method argument</param>
-        public static ILoggingBuilder AddAzureWebAppDiagnostics(this ILoggingBuilder builder)
+        /// <param name="customPrefix"></param>
+        /// <returns></returns>
+        public static ILoggingBuilder AddAzureWebAppDiagnostics(this ILoggingBuilder builder, string customPrefix = null)
```
Comment (davidfowl) [inline src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:26]: @Pilchie is this a binary breaking change?

Comment (Pilchie) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:26]: Absolutely.

Comment (Pilchie) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs:26]: Overloads are binary breaking safe, optional parameters are not - think about how they work, the method always receives two arguments, it's just that if you don't specify it, the compiler burns in the default value at the call-site.

Comment (yogigrantz) [reply src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs]: My bad, I removed the optional parm and went ahead and created an overload instead. But CI still shows this optional parm error, even though I renamed the parameter.
@Pilchie @davidfowl  
[SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters"

**Comment by yogigrantz** [comment]
Please discard my version of AspNetCore.sln. It was inadvertently pushed to my repository

**Comment by yogigrantz** [comment]
Could someone please help me out? I accidentally pushed AspnetCore.sln. Now it is in conflict. I'd appreciate if someone with write access can resolve conflicts by replacing my version with the current master version. Thank you!

**Comment by BrennanConroy** [comment]
You should be able to fix it fairly easily:
```
git revert --hard HEAD~2
# redo the parameter naming change
git add <file>
git commit -m "param rename"
git push -f
```

**Comment by yogigrantz** [comment]
@BrennanConroy when I typed git revert --hard HEAD~2 it would not take. it gave me the help menu, shown in this screenshot:
gitCapture

**Comment by BrennanConroy** [comment]
Whoops, I meant reset. `git reset --hard HEAD~2`

**Comment by yogigrantz** [comment]
Brennan: I followed your steps. Not sure if the .sln file was recovered? But could I have another rebuild please? I think the last build broke with #L39

**Comment by yogigrantz** [comment]
@wtgodbe  : is there anything I could do to fix this error ?src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs(39,39): error RS0016: (NETCORE_ENGINEERING_TELEMETRY=Build) Symbol 'AddAzureWebAppDiagnostics' is not part of the declared API.

**Comment by dougbu** [comment]
> is there anything I could do to fix this error ?

If you have Visual Studio 16.8 or later installed,
1. `.\restore.cmd` to ensure the .dotnet/ folder is up-to-date
2. `.\startvs.cmd src\Logging.AzureAppServices\src\Microsoft.Extensions.Logging.AzureAppServices.csproj`
3. build the project e.g. *[F6]**
4. click on the RS0016 message in the error window
5. use the light bulb menu or right click the line and add the method to the public API files
6. commit the change and update this branch 😺

**Comment by yogigrantz** [comment]
Is VS 16.8 available to download? because when I checked my VS it says 16.7.6 and that's the latest update. When I followed your steps I did not get any errors. I took the screenshots:
prepOK
buildsOK

**Comment by dougbu** [comment]
> Would this work in VS 16.7.6?

@mavasani @sharwell do the public API analyzers and fixers work correctly in 16.7.6❔ I'm surprised @yogigrantz's build was successful.

@yogigrantz it's possible VS thought the project was up-to-date. You may need to rebuild instead of build to get the error seen on the CI.

Another idea would be to use the public preview version of Visual Studio. Easy way to get that is `.\eng\scripts\InstallVisualStudio.ps1 -Channel Preview -Edition Community`.

**Comment by yogigrantz** [comment]
@dougbu  : The rebuild works both in 16.7.6 and 16.8 Preview 5.0.  When I downloaded preview 3.1 it gave me version 5.0 btw so I could not get 3.1.

The .\restore.cmd failed on 16.8 preview 5.0. 

Also, when I ran this script: .\eng\scripts\InstallVisualStudio.ps1 -Channel Preview -Edition Community it was pointing to version 16.7.6

**Comment by dougbu** [comment]
> The rebuild works both in 16.7.6 and 16.8 Preview 5.0.

I don't understand this and hope @mavasani or @sharwell can help out here.

> When I downloaded preview 3.1 it gave me version 5.0 btw so I could not get 3.1

I didn't mention a specific preview of VS 16.8. Preview 5 is fine.

> it was pointing to version 16.7.6

What pointed to version 16.7.6❔ If you mean the version of VS that startvs.cmd chose to start, That would mean the default is still your previous VS installation.

You can change the association for `*.csproj` files to use the Preview version of VS by default. Or, you can set `$env:VSINSTALLDIR` to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community_Pre"` before using .\startvs.cmd. The InstallVisualStudio.ps1 command I provided should have installed VS 16.8 there.

**Comment by mavasani** [comment]
@dougbu @yogigrantz You are likely hitting https://github.com/dotnet/msbuild/issues/3046, which is applicable to every MSBuild warning, not just analyzer warnings.

**Comment by yogigrantz** [comment]
@dougbu : What pointed to version 16.7.6❔  Sorry for the confusion. when I copied your command line, it errored out. So I went ahead and opened InstallVisualStudio.ps1 with powershell and ran it manually. At that point it opened up the Installer option dialog for Enterprise edition, 16.7.6 . After that I changed the value for $Edition and $Channel as shown on the screenshot, but all it does is open the installer dialog with items that I already installed checked out. Is this step for verifying whether I have the correct Visual Studio?
VSInstaller

**Comment by yogigrantz** [comment]
@mavasani : In our case we don't have any warning though. I build with --no-incremental and still, no warning

nowarning

**Comment by dougbu** [comment]
@yogigrantz for the questions you asked me: The InstallVisualStudio.ps1 file is intended to run from within PowerShell and we don't have a `.bat` or `.cmd` file anywhere to make it easier to use from `cmd`. When run without `-quiet` or `-passive`, the script does indeed open the installer dialogue. You need to click `Install`, `Modify`, or `Update` to complete the installation or upgrade.

**Comment by yogigrantz** [comment]
@dougbu ok I followed thru with update and everything went well. I did another build, it built successfully. 0 Warning 0 Error. There is no changed file in my repository, so there is nothing to commit or push. @mavasani  : when there is no warning and no error, does this situation in  dotnet/msbuild#304 still apply? Could you please advise how I should resolve it?

**Comment by yogigrantz** [comment]
Hi, since my repository was too far behind I deleted it and reforked and recloned aspnetcore from the master branch. The current global.json says sdk "version": "6.0.100-alpha.1.20523.3". Should I download this sdk to build the solution, because I have 5.0-rc2 in my machine and it would not build this solution now. If I modify global.json chances are, when I try to merge it would fail the build again. Please advise, thank you!
@dougbu  @mavasani @wtgodbe

**Comment by dougbu** [comment]
> Should I download this sdk to build the solution, because I have 5.0-rc2 in my machine and it would not build this solution now.

Run the `./build.cmd` script w/ pretty much any option to install the required SDK and runtimes in the .dotnet/ folder. The `startvs.cmd` ensures Visual Studio uses that folder and not the globally-installed `dotnet`. All command-line builds also ignore the globally-installed `dotnet`.

**Comment by yogigrantz** [comment]
Started over from fresh copy of dotnetcore master branch 10/3/2020 -> pull request #27383. I updated / fixed the UnitTest and added the overload in  src/Logging.AzureAppServices/src/PublicAPI.Unshipped.txt  . Now getting only 3 failures
. Could you please let me know whether this failure come from the CI or from the application? Thank you!
@dougbu  @wtgodbe

**Comment by dougbu** [comment]
@yogigrantz you need to use Visual Studio to update the src/Logging.AzureAppServices/src/PublicAPI.Unshipped.txt file. It should include the added `AddAzureWebAppDiagnostics` overload.

You may need to remove the .\artifacts\bin\Microsoft.Extensions.Logging.AzureAppServices\ folder and perhaps .\artifacts\obj\Microsoft.Extensions.Logging.AzureAppServices\ to ensure the VS build actually hits the error.

**Comment by yogigrantz** [comment]
Transferring to #27383 -> Fresh reclone
