### ISSUE TITLE
Razor build regression in .NET 6.0 when class and namespace have the same name

### ISSUE THREAD

**Issue by NCarlsonMSFT** [dotnet/aspnetcore#34607]
I've run into an issue in the Service Fabric tools where the templates do not work on .NET 6.0 due to the namespace and service name having the same name (this workes in .NET 5.0).

The specific error in .NET 6.0 is:
\TestProject\Pages\_ViewImports.cshtml(1,7): error CS0138: A 'using namespace' directive can only be applied to namespaces; 'TestProject' is a type not a namespace. Consider a 'using static' directive instead [\TestProject\TestProject.csproj]

A script for making a minimized repro:
```powershell
dotnet new webapp -o 'TestProject' -f 'net5.0'

# Update the project to target 5.0 and 6.0
$projFile = Get-Content -Path "TestProject\TestProject.csproj"
$projFile = $projFile -replace "<TargetFramework>net5.0</TargetFramework>", "<TargetFrameworks>net5.0;net6.0</TargetFrameworks>"
Set-Content -Path "TestProject\TestProject.csproj" -Value $projFile

# Add the conflicting class name
Set-Content -Path "TestProject\TestProject.cs" -Value "namespace TestProject { internal class TestProject { } }"

# Build in 5.0
dotnet build 'TestProject\TestProject.csproj' -f 'net5.0' -v q | Out-File 'net5.log'
if ($?) {
    Write-Host "Building 5.0 worked" -ForegroundColor 'Green'
}
else {
    Write-Host "Building 5.0 failed" -ForegroundColor 'Red'
}

# Build in 6.0
dotnet build 'TestProject\TestProject.csproj' -f 'net6.0' -v q | Out-File 'net6.log'
if ($?) {
    Write-Host "Building 6.0 worked" -ForegroundColor 'Green'
}
else {
    Write-Host "Building 6.0 failed" -ForegroundColor 'Red'
}
```

Additional context: I discovered when attempting to make the minimized repro that if the class TestProject is public this fails in 5.0 too.

**Comment by pranavkm** [comment]
Thanks for the issue report. This is a side-effect of the work we did as part of https://github.com/aspnet/Announcements/issues/459. Views are part of the regular assembly and as such have access to internal types from that assembly. The combination of C#'s namespace resolution and the presence of `@using TestProject` in the `_ViewImports.cshtml` cause the compiler to now resolve the type rather than the namespace.

One  workaround if this is much more extensive in your real project would be to globally qualify your usings (`@using global::TestProject`) or pick a different `@namespace` for your Razor Pages / views to avoid the conflict.

**Comment by NCarlsonMSFT** [comment]
@pranavkm This is showing up in the new project case for Service Fabric .NET Core services. The Service Fabric templates start with the ASP.NET Core templates and then add the Service Fabric specific files which include a class with the same name as the project. It is possible for us to update the new project logic, but there is also a large number of exiting projects out there that will be impacted by this change when migrating to .NET 6.

**Comment by mkArtakMSFT** [comment]
@NCarlsonMSFT unfortunately we are unable to prioritize this fix for the upcoming 6.0 release. Given that there is a relatively easy workaround that you can take on your side, we're moving this issue further to consider for .NET 7 release.
