### ISSUE TITLE
[9.0-preview.5] Endpoint with nullable parameter no longer generates code with Request Delegate Generator

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#55840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using version `9.0.100-preview.5.24272.3` of the .NET SDK from daily builds, an endpoint associated with a method that has a `string[]?` parameter is no longer having an endpoint generated an produces a RDG003 warning.

```console
Error: /home/runner/work/adventofcode/adventofcode/src/AdventOfCode.Site/Program.cs(135,1): error RDG003: Unable to statically resolve parameter named 'arguments' for endpoint. Compile-time endpoint generation will skip this endpoint and the endpoint will be generated at runtime. For more information, please see https://aka.ms/aspnet/rdg-known-issues (https://learn.microsoft.com/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/RDG003) [/home/runner/work/adventofcode/adventofcode/src/AdventOfCode.Site/AdventOfCode.Site.csproj]
```

The error is not generated with .NET 8 or .NET 9 preview 4.

The signature of the endpoint is the following ([code](https://github.com/martincostello/adventofcode/blob/fe22226c9428f995e396a9ee5f81b8c7ae6dbd7d/src/AdventOfCode.Site/PuzzlesApi.cs#L55-L64)):

```chsarp
internal static async Task<IResult> SolvePuzzleAsync(
    int year,
    int day,
    HttpRequest request,
    [FromForm] string[]? arguments,
    IFormFile? resource,
    PuzzleFactory factory,
    TimeProvider timeProvider,
    ILogger<Puzzle> logger,
    CancellationToken cancellationToken)
```

### Expected Behavior

Request Delegate Generator successfully generates code for this endpoint.

### Steps To Reproduce

1. Clone https://github.com/martincostello/adventofcode/pull/1663/commits/fe22226c9428f995e396a9ee5f81b8c7ae6dbd7d#diff-f905acb7a057826fd183f2558445347c59e1cf0304dc0499d9f5e0ae4a523ebe
2. Run `build.ps1` in the root of the repository.

### .NET Version

9.0.100-preview.5.24272.3

**Comment by martincostello** [comment]
Looks like this was broken by #55465.

Specifically, this code addition:

https://github.com/dotnet/aspnetcore/blob/83573c72d12e1c2018805bc5d461d730bcb9dcc4/src/Http/Http.Extensions/gen/StaticRouteHandlerModel/EndpointParameter.cs#L110-L119

**Comment by captainsafia** [comment]
@martincostello Thanks for reporting this bug and apologies for the delay as I work through my backlog here! 😅 

I believe the reason this is happening is because the target type is a `string[]` in particular. The condition that you referenced above needs an additional `(IsArray && ElementType.SpecialType == SpecialType.System_String)` check since we don't don't generate a parsability method for string types out of `TryGetParsability`.

PR incoming....

**Comment by martincostello** [comment]
No problem - I did take a look at fixing it myself, but I wasn't sure if it was intentional or not so noped out of it 😅

Glad it's a quick fix!
