### ISSUE TITLE
Blazor 6.0 app fails to compile in 8.0.200.

### ISSUE THREAD

**Issue by wasabii** [dotnet/aspnetcore#54019]
I have a Blazor WASM application, targeting TFM 6.0. As of two hours ago a build in my CI/CD pipeline just began failing:

>D:\a\1\s\src\xxx\Program.cs(23,40): error CS0118: 'App' is a namespace but is used like a type [D:\a\1\s\src\xxx\xxx.csproj]

Turns out it was using SDK 8.0.101, but with rollforward latestfeature. As of two hours ago it began installing 8.0.200.

So, something in 8.0.200 changed related to this.

I'm getting this warning as well, which I wasn't getting a couple hours ago:

>CSC : warning CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. [D:\a\1\s\src\xxx\xxx.csproj]

I haven't dug into anything yet to provide more information than that presently.

So, something with source generators changed. Probably the thing that's supposed to be compiling App.razor into a class. I'm surprised a minor release like this changed anything at all....

**Comment by Kamys85** [comment]
Please download and use Visual Studio Community Preview upgraded to "17.10.0 Preview 1.0". It should resolve problem of `SourceGenerators.dll` in wrong version.

**Comment by wasabii** [comment]
Download it where? This is a build machine.

**Comment by dipakboyed** [comment]
@Kamys85 , our builds are hosted agents in Azure DevOps controlled by 1ES.
