### ISSUE TITLE
Bug 2880585: [dotnet-sdk-11.0.100-preview.3.26174.105] The radzen blazor menu cannot expand with error: Uncaught TypeError: t.DispatchMouseEvent is not a function.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#66110]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After we retarget radzen blazor to .net11.0 and build with dotnet-sdk-11.0.100-preview.3.26174.105, we run the app and click to expand the menu, but the menu cannot expand and show error:``` Uncaught TypeError: t.DispatchMouseEvent is not a function```.

**Application Name:** radzen-blazor
**OS**: Windows 11 25H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-11.0.100-preview.3.26174.105

**GitHub Link:** https://github.com/radzenhq/radzen-blazor

 **Or checking App Source from**: (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2880585)

**Verify Scenarios:**
1). Windows 11 25H2 AMD64 + dotnet-sdk-11.0.100-preview.3.26172.108: Pass
2). Windows 11 25H2 AMD64 + dotnet-sdk-11.0.100-preview.3.26174.105: Fail
3). Windows 11 25H2 AMD64 + dotnet-sdk-11.0.100-preview.3.26179.102: Fail

### Expected Behavior

The menu can be expanded.

### Steps To Reproduce

1. Retarget the project to net11.0. (Replace net10 with net11 in the entire solution.)
    ```<TargetFrameworks>net11.0</TargetFrameworks>```

2. Add PackageReference in Radzen.Blazor.csproj.
```<PackageReference Include="Microsoft.AspNetCore.Components" Condition="'$(TargetFramework)' == 'net11.0'" Version="11.*-*" />
<PackageReference Include="Microsoft.AspNetCore.Components.Web" Condition="'$(TargetFramework)' == 'net11.0'" Version="11.*-*" />
```
3. Build the project ```RadzenBlazorDemos.Host``` with dotnet-sdk-11.0.100-preview.3.26174.105. (Add global.json: ```{"sdk": {"version": "11.0.100-preview.3.26174.105"}}```)
4. Lanuch RadzenBlazorDemos.Host.exe.
5. Go to http://localhost:5000/get-started.
6. Expand the “DataGrid” item.

### Exceptions (if any)

The menu cannot expand with error in console:
```
blazor.web.js:1 Uncaught TypeError: t.DispatchMouseEvent is not a function
    at blazor.web.js:1:16005
    at blazor.web.js:1:18987
    at M (blazor.web.js:1:19374)
    at blazor.web.js:1:19424
    at Object.invokeWhenHeapUnlocked (blazor.web.js:1:186856)
    at blazor.web.js:1:191014
    at M (blazor.web.js:1:19414)
    at N (blazor.web.js:1:15485)
    at F.dispatchGlobalEventToAllElements (blazor.web.js:1:22166)
    at F.onGlobalEvent (blazor.web.js:1:21569)
```

### .NET Version

11.0.100-preview.3.26174.105

### Anything else?

**dotnet --info**
```
.NET SDK:
 Version:           11.0.100-preview.3.26174.105
 Commit:            499c5b40b9
 Workload version:  11.0.100-manifests.8fe6e2b8
 MSBuild version:   18.6.0-preview-26174-105+499c5b40b

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.26200
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\11.0.100-preview.3.26174.105\

Host:
  Version:      11.0.0-preview.3.26174.105
  Architecture: x64
  Commit:       499c5b40b9

.NET SDKs installed:
  11.0.100-preview.3.26174.105 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 11.0.0-preview.3.26174.105 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 11.0.0-preview.3.26174.105 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 11.0.0-preview.3.26174.105 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
@dotnet-actwx-bot @dotnet/compat

**Comment by oroztocil** [comment]
This is related to a recent sequence of PRs that introduced new functions in the JS interop API (including `DispatchMouseEvent` mentioned in the error), and were later reverted. See:

- https://github.com/dotnet/aspnetcore/pull/65897
- https://github.com/dotnet/aspnetcore/pull/65895
- https://github.com/dotnet/aspnetcore/pull/66068
- https://github.com/dotnet/aspnetcore/pull/66069

As such, the problem should resolve itself in a newer build once all commits have flown properly.

@Junjun-zhao May I ask you for re-testing this with a current build (or wait some time and then re-test)?

**Comment by Junjun-zhao** [comment]
> This is related to a recent sequence of PRs that introduced new functions in the JS interop API (including `DispatchMouseEvent` mentioned in the error), and were later reverted. See:
> 
> * [[blazor][wasm] JSExport for events #65897](https://github.com/dotnet/aspnetcore/pull/65897)
> * [[blazor][wasm] Convert more interop to JSImport #65895](https://github.com/dotnet/aspnetcore/pull/65895)
> * [[blazor][wasm] Revert JSExport for events (#65897) #66068](https://github.com/dotnet/aspnetcore/pull/66068)
> * [[blazor][wasm] Revert Convert more interop to JSImport (#65895) #66069](https://github.com/dotnet/aspnetcore/pull/66069)
> 
> As such, the problem should resolve itself in a newer build once all commits have flown properly.
> 
> [@Junjun-zhao](https://github.com/Junjun-zhao) May I ask you for re-testing this with a current build (or wait some time and then re-test)?

Sure. We will re-test with a new build next week.

**Comment by Junjun-zhao** [comment]
Hi @oroztocil, we verified with dotnet-sdk-11.0.100-preview.3.26203.107, this issue still reproduces. Could you please help confirm if this build has included the fix? And is it a blocker for .NET 11 Preview 3?

**Comment by Junjun-zhao** [comment]
Hi @oroztocil, this issue still reproduces on the final build dotnet-sdk-11.0.100-preview.3.26207.106 for .NET 11 preview3, could you help confirm if this is a blocker for P3?

**Comment by pavelsavara** [comment]
@Junjun-zhao 
Have you also updated PackageReference to match the Net11 preview ?
`<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="<version>" />` ?

We don't support compatibility between major versions of SDK and components.

**Comment by oroztocil** [comment]
I re-tested the problem and it does not reproduce with the final P3 version `11.0.100-preview.3.26207.106` if you use the matching package version, as recommended by @pavelsavara.

@Junjun-zhao If you still reproduce the issue, please provide the actual steps that you perform while testing this. From my experience, the reproduction steps in your report are not enough to successfully build and run the application so the problem may be elsewhere - in this case in the way the projects are exactly configured.

**Comment by Junjun-zhao** [comment]
Thanks @pavelsavara @oroztocil. After we updated the PackageReference, this issue does not reproduce.
