### ISSUE TITLE
Spurious Error Message: No Suitable Method found to override after upgrade from 6 - 7 Preview 3

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/aspnetcore#41212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Server app which I just upgraded to 7 Preview 3.

After upgrading, every component file which overrides the OnInitializedAsync methods generates an exception:  

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'Toaster.OnInitializedAsync()': no suitable method found to override	CDS	C:\Dev\dev.azure.com-CSSLLC\CDS-Blazor-Net6\CDS Blazor\CDS-NET6\CDS\Components\Toaster.razor.cs	26	Active
```

If I update the file to add the base class, the error is resolved.  This was not required in .net 6. Note that in Visual Studio, the Error will show for about a minute, and then all of these types of errors will disappear.  However, when I try to build the app, the error appears again.

`public partial class Toaster : ComponentBase`

I also notice this warning:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8785	Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'KeyNotFoundException' with message 'The given key was not present in the dictionary.'	CDS	C:\Dev\dev.azure.com-CSSLLC\CDS-Blazor-Net6\CDS Blazor\CDS-NET6\CDS\CSC	1	Active
```

### Expected Behavior

The project will build and run.

### Anything else?

I am using Visual Studio 2022 Preview 3

.net core 7.0.0-preview.3.22178.4

Any advice would be appreciated.

**Comment by gregoryagu** [comment]
I reverted the project back to .net 6, but i am still getting the same error as above.  It seems after I installed the .net 7 SDK that this issue started.  

I have tried creating a Test Blazor Server App and it runs fine, so not sure what is up with this.

**Comment by gregoryagu** [comment]
I have also tried rebooting the machine.

**Comment by gregoryagu** [comment]
After uninstalling .net 7 Preview 3 SDK, the .net 6 version correctly builds and runs again, so it seems to be something with the .net 7 SDK Install.
