### ISSUE TITLE
Blazor preview 8.0.0-preview.4.23260.4 startup error

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#48298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating to 8.0.0-preview.4.23260.4, the hosted Blazor application no longer starts with the following error:

### Exceptions (if any)

blazor.webassembly.js:1 Error: Failed to start platform. Reason: TypeError: r.withStartupOptions is not a function
    at Wt (blazor.webassembly.js:1:54519)

Code which works before the update: https://github.com/damienbod/Hostedblazor8Aad

### Steps To Reproduce

Update nuget packages to actual preview

### Expected Behavior

should start

### .NET Version

8

**Comment by danroth27** [comment]
I tried cloning the project and updating the packages to the .NET 8 Preview 4 versions and it ran fine for me. Since the error is on the JavaScript side, is this maybe a browser caching issue?

**Comment by danroth27** [comment]
@damienbod Can you push a .NET 8 branch to your repro that shows exactly what you did to upgrade the solution to .NET 8?

**Comment by damienbod** [comment]
Hi @danroth27 Thanks for your feedback

Here are the changes:

https://github.com/damienbod/Hostedblazor8Aad/pull/1

When I try to start now (Empty cache and hard reload) I get the error.

Greetings Damien

**Comment by danroth27** [comment]
Hmm, I tried your branch and it still runs for me:
![image](https://github.com/dotnet/aspnetcore/assets/1874516/fd9c26bc-f3ab-41bc-b436-f891eb8e2206)

Can you try deleting your bin and obj folders and rebuilding?

Also, what .NET SDKs do you have installed? `dotnet --info`

**Comment by damienbod** [comment]
SDKs
```
.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.116 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.311 [C:\Program Files\dotnet\sdk]
  7.0.105 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23225.8 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]
```

Deleted the bin/obj and now it works. Sorry about that, must remember to delete next time.

Thanks for your help

Greetings Damien
