### PR TITLE
Support validation for C# union cases

### LINKED ISSUE #68268: Support unions in ValidationsGenerator
ValidationsGenerator today doesn't work with unions. What likely needs to happen is:

- Update the source generator so that it recognize union, and generates validatable type info for all the union cases.
- The validations generator shouldn't ignore validating the `Value` property. This property is likely to have `IsImplicitlyDeclared = true` which the generator skips today.

### PR DESCRIPTION
**Pull request by DeagleGross**
# Support validation for C# union cases

Update the validation source generator to discover validatable C# union case types through `ITypeSymbol.UnionCaseTypes`.

## Description

`Microsoft.Extensions.Validation.ValidationsGenerator` obtains logic to properly handle C# union cases. If it discovers C# union, it looks into union case types and adds validation of the case types if exist.

Fixes #68268

## Customer Impact

A proper behavior for c# union support in validations.

## Regression?

- [ ] Yes
- [x] No

## Risk

- [ ] High
- [ ] Medium
- [x] Low

New functionality for new C# 15 feature

## Verification

- [ ] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

File: src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs [hunk 1]
```diff
@@ -167,7 +182,27 @@ internal static bool ShouldSkipProperty(
...
+    private static bool IsUnionValueProperty(IPropertySymbol property)
+        => property is
+        {
+            Name: "Value",
+            IsImplicitlyDeclared: true,
+            DeclaredAccessibility: Accessibility.Public,
+            ContainingType: { } containingType,
+        } && IsUnionType(containingType);
+
+#pragma warning disable RSEXPERIMENTAL006 // Union symbol APIs were still annotated as experimental in this branch's compiler.
```
Comment (Youssef1313) [inline src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: I assume they are no longer experimental right?
Were there any breaking changes done in-between?

File: src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs [hunk 2]
```diff
@@ -167,7 +182,27 @@ internal static bool ShouldSkipProperty(
...
+    private static bool IsUnionType(ITypeSymbol typeSymbol) => typeSymbol.IsUnion;
+
+    private static ImmutableArray<ITypeSymbol> GetUnionCaseTypes(ITypeSymbol typeSymbol) => typeSymbol.UnionCaseTypes;
```
Comment (Youssef1313) [inline src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: nit: inline this single line method?

File: src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs [hunk 3]
```diff
@@ -167,7 +182,27 @@ internal static bool ShouldSkipProperty(
...
+        => property is
+        {
+            Name: "Value",
+            IsImplicitlyDeclared: true,
+            DeclaredAccessibility: Accessibility.Public,
+            ContainingType: { } containingType,
+        } && IsUnionType(containingType);
+
+#pragma warning disable RSEXPERIMENTAL006 // Union symbol APIs were still annotated as experimental in this branch's compiler.
+    private static bool IsUnionType(ITypeSymbol typeSymbol) => typeSymbol.IsUnion;
```
Comment (Youssef1313) [inline src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: nit: inline this single line method?

Comment (Youssef1313) [inline src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: > src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs(195,75): error CS1061: 'ITypeSymbol' does not contain a definition for 'IsUnion' and no accessible extension method 'IsUnion' accepting a first argument of type 'ITypeSymbol' could be found (are you missing a using directive or an assembly reference?)

Do we have builds that use older MS.CA version? :/

File: src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs (hunk 1 above)
Comment (DeagleGross) [reply src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: I had problems building them - maybe I need to update sdk or whatever on my machine. I'll figure it out. Decided to push to test error on CI

Comment (Youssef1313) [reply src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: That's because we pin MicrosoftCodeAnalysisVersion_LatestVS to 4.13.
It should hopefully be safe to bump to 5.x. I think in VS 2026 we only support latest, if I'm not mis-remembering the support policy for VS 2026.

Comment (Youssef1313) [reply src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: One alternative that NetAnalyzers used to do in the past was to use reflection but we should avoid that if possible.

Comment (DeagleGross) [reply src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: bumped to 5.11.0-...; lets see if CI will be happy

Comment (DeagleGross) [reply src/Validation/gen/Parsers/ValidationsGenerator.TypesParser.cs]: I fixed tests after upgrading to 5.11. Should be ready-for-review now

File: src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/FrameworkParametersCompletionProviderTests.cs [hunk 4]
```diff
@@ -592,11 +592,11 @@ private static bool TryParse(string s, IFormatProvider provider, out CustomParsa
 ");
 
         // Assert
-        Assert.Empty(result.Completions.ItemsList);
+        Assert.DoesNotContain(result.Completions.ItemsList, i => i.DisplayText == "id");
```
Comment (Youssef1313) [inline src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/FrameworkParametersCompletionProviderTests.cs:596]: I guess this must be related to the Roslyn upgrade. A bit of explanation on what `ItemsList` now contains is appreciated (if you remember immediately - otherwise I can run it locally to understand).

**Review by Youssef1313 — APPROVED** [review]
LGTM. I would personally prefer bumping to the minimum required Roslyn version (5.9, I think) instead of the latest 5.11.

But if @wtgodbe confirms the upgrade is fine, that's fine for me.

I also checked that the .NET 11 in VMR build is on 5.11: https://github.com/dotnet/dotnet/blob/release/11.0/src/roslyn/eng/Versions.props so it should be good.

File: src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/FrameworkParametersCompletionProviderTests.cs (hunk 4 above)
Comment (DeagleGross) [reply src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/FrameworkParametersCompletionProviderTests.cs:596]: Ye, that's related to Roslyn upgrade. Before it was not providing any completions, but now it provides some, but we are checking that there is no "id" (which is a  route parameter) - because its invalid in the context. So only sane completions are displayed.

Consider example:
```csharp
class Program
{
    static void Main()
    {
        EndpointRouteBuilderExtensions.MapGet(null, @""{id}"", (CustomParsableType $$
    }
}

public class CustomParsableType
{
    private static bool TryParse(string s, IFormatProvider provider, out CustomParsableType result)
    {
        result = new CustomParsableType();
        return true;
    }
}
```

could get completions like (based on test output)
```
customParsableType
customParsable
parsableType
custom
type
var
string
... (other keywords)
```

It's not a breaking behavior for users, since its what Roslyn provides and it does not provide invalid completions. We should be good. I added a comment to explain that

**Review by Youssef1313 — APPROVED** [review]

**Review by artl93 — APPROVED** [review]
Approved. New feature for .NET 11
