### ISSUE TITLE
Blazor WebAssembly doesn't compile after upgrade to 8.0.2, then shows blank page

### ISSUE THREAD

**Issue by mattfrear** [dotnet/aspnetcore#54219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Latest Visual Studio 2022 - 17.8.7

File -> New "Blazor WebAssembly Standalone App" -> "BlazorApp1"

It doesn't compile in Visual Studio:
```
1>CSC : warning CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.201\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'.
1>C:\code\local\BlazorApp1\BlazorApp1\Program.cs(1,7,1,17): error CS0246: The type or namespace name 'BlazorApp1' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "BlazorApp1.csproj" -- FAILED.
```

I'm still new to Blazor - but I found a workaround which makes it compile, which is to add `App.razor.cs`:
```
using Microsoft.AspNetCore.Components;

namespace BlazorApp1;

public partial class App : ComponentBase
{
}
```

With this workaround, it compiles, but when debugging shows a blank page:
![image](https://github.com/dotnet/aspnetcore/assets/169179/60196427-90bc-480a-ae74-22ea4d80432d)

### Expected Behavior

- A new Project should compile
- When it runs it should show the Hello World and Weather forecast pages

### Steps To Reproduce

File -> New "Blazor WebAssembly Standalone App" -> "BlazorApp1"

### .NET Version

8.0.201

### Anything else?
Latest Visual Studio 2022 - 17.8.7
Possibly a duplicate of https://github.com/dotnet/aspnetcore/issues/54196

**Comment by mattfrear** [comment]
I thought I was running the latest Visual Studio 2022, because I upgraded it this morning from Visual Studio's Notifications window.

Evidently I wasn't running the latest. The latest is 17.9.1, which doesn't have this issue.
