### PR TITLE
Emit diagnostics for unsupported RDG scenarios

### LINKED ISSUE #47339: RDG does not support private parameter and return types
Given the code:

```csharp
public class MyClass
{

    public static void MyMethod(IEndpointRouteBuilder app)
    {
        app.MapPost("/test-param", (MyDto param) => { });
        app.MapPost("/test-return", () => new MyDto());
    }

    private class MyDto { }
}
```

RDG generates code that fails to compile because `MyDto` is a private type. The lines that cause the compilation failure by referencing the private type are basically the same lines that fail with an undefined `TUser` in #47338 which is the equivalent issue about generic types.

We can skip generating `MapPost` and similar methods when we see a private type in the delegate signature and suggest using internal types instead. I don't think we really have an alternative unless we could somehow generate our `Map` extension methods directly in the same class/struct the user is calling it from. I don't know of any plans for that.

```
GeneratedRouteBuilderExtensions.g.cs(73,111): error CS0122: 'MyClass.MyDto' is inaccessible due to its protection level
GeneratedRouteBuilderExtensions.g.cs(88,109): error CS0122: 'MyClass.MyDto' is inaccessible due to its protection level
```

### LINKED ISSUE #49384: Request Delegate Generator fails to compile code with CS0246 error for endpoint with generic type parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an internal application that has a user interface where various properties of a configuration object can be changed independently. To reduce duplication for this operations, various HTTP PATCH endpoints with different URLs call through a generic method that maps the endpoint based on a code pattern.

The method is essentially this where boilerplate wraps the invocation of a delegate with a generic parameter:

```csharp
private static RouteHandlerBuilder MapRepositoryUpdate<T>(
    this IEndpointRouteBuilder endpoints,
    string pattern,
    Func<IConfigurationRepository, RepositoryId, T, CancellationToken, Task<bool>> operation)
{
    return endpoints.MapPatch(pattern, async (
        long installationId,
        long repositoryId,
        [FromBody] Payload<T> request,
        InstallationService service,
        IConfigurationRepository repository,
        CancellationToken cancellationToken) =>
    {
        if (!await service.UserHasAccessToRepositoryAsync(installationId, repositoryId))
        {
            return Results.NotFound();
        }

        await repository.EnsureRepositoryAsync(repositoryId, cancellationToken);

        return await operation(repository, new(repositoryId), request.Value, cancellationToken) switch
        {
            false => Results.Conflict(),
            true => Results.NoContent(),
        };
    }).RequireAuthorization();
}
```

When attempting to compile this application with the Request Delegate Generator enabled the compilation fails with the following errors:

```
src\MyApplication\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(43,118): error CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?) [src\MyApplication\MyApplication.csproj]
src\MyApplication\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(58,140): error CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?) [src\MyApplication\MyApplication.csproj]
```

It appears that the generator is not correctly taking into account the use of generics and is trying to use the identifier `T` literally as a type named `T` rather than as a generic parameter with that name.

When I tried to make the smallest repro I could with a one file application the endpoint would compile, so I think the issue may be related to the way the code is structured in the original application in terms of namespaces etc.

I've added an application that reproduces the error in [this repository](https://github.com/martincostello/rdg-generics-repro). There's probably more code that needed, but it's relatively minimal.

Note that the application will not actually run as I've stripped it down to just compiling so is 
missing various services registrations etc. It's just enough required to compile it successfully if the Request Delegate Generator is disabled.

### Expected Behavior

The application compiles and the endpoints behave at runtime as expected.

### Steps To Reproduce

1. Clone the [martincostello/rdg-generics-repro](https://github.com/martincostello/rdg-generics-repro) repository
2. Run `dotnet build`

### Exceptions (if any)

_No response_

### .NET Version

8.0.100-preview.6.23330.14

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
- Emit warnings for generics captured in parameters or response types (fixes https://github.com/dotnet/aspnetcore/issues/49384)
- Emit warnings for private/protected types captured in parameters or response types (fixes https://github.com/dotnet/aspnetcore/issues/47339)
- Fix warning for anonymous types in awaitable methods

### CODE REVIEW

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs [hunk 1]
```diff
@@ -128,4 +128,117 @@ public async Task SourceMapsAllPathsInAttribute()
...
+        var source = isAsync
+            ? @"app.MapGet(""/hello"", async (int value) => await Task.FromResult(new { Delay = value }));"
+            : @"app.MapGet(""/hello"", (int value) => new { Delay = value });";
+        var (generatorRunResult, compilation) = await RunGeneratorAsync(source);
+
+        // Emits diagnostic but generates no source
+        var result = Assert.IsType<GeneratorRunResult>(generatorRunResult);
+        var diagnostic = Assert.Single(result.Diagnostics);
+        Assert.Equal(DiagnosticDescriptors.UnableToResolveAnonymousReturnType.Id, diagnostic.Id);
+        Assert.Empty(result.GeneratedSources);
```
Comment (BrennanConroy) [inline src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs:146]: Should there be test(s) for emitting source for valid endpoints when invalid endpoints are also used? The diagnostic messages sort of imply that generation continues, and the messages could be suppressed technically.

File: src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/DiagnosticEmitter.cs [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+internal static class DiagnosticEmitter
+{
+    public static void EmitRequiredDiagnostics(this EndpointResponse response, List<Diagnostic> diagnostics, Location location)
+    {
+        if (response.ResponseType is ITypeParameterSymbol)
+        {
+            diagnostics.Add(Diagnostic.Create(DiagnosticDescriptors.TypeParametersNotSupported, location));
+        }
+        if (response.ResponseType?.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected)
```
[the remark this answers is not in the document]
Comment (captainsafia) [reply src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/DiagnosticEmitter.cs:17]: > Unless these are meant to be else if

I debated this but I've always like the upfront disclosure you get when all the warnings are emitted at once instead of the progressive disclosure that allows you to keep fixing things until you get it right.

File: src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Endpoint.cs [hunk 3]
```diff
@@ -55,7 +50,13 @@ public Endpoint(IInvocationOperation operation, WellKnownTypes wellKnownTypes, S
 
         for (var i = 0; i < method.Parameters.Length; i++)
         {
-            var parameter = new EndpointParameter(this, method.Parameters[i], wellKnownTypes);
+            var parameterSymbol = method.Parameters[i];
+            parameterSymbol.EmitRequiredDiagnostics(Diagnostics, Operation.Syntax.GetLocation());
+            if (Diagnostics.Count > 0)
```
[the remark this answers is not in the document]
Comment (captainsafia) [reply src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Endpoint.cs:55]: > What if we emit info diagnostics, or diagnostics from a different part of the generator unrelated to this endpoint?

At the moment, we're strictly using diagnostics as a way to indicate that some aspect of the endpoint is wrong and we can't statically generate it.

If we do decide to start emitting info-level diagnostics (I dunno how meaningful that would be for a source generator given that it's only visible in builds triggered from the IDE), we'd have to consider other aspects of the implementation, such as the way we use the lack of diagnostics to determine if we haven't been able to generate an endpoint.

All in all, I feel safe with the simplicity of `.Count > 0` here given the constraints were operating under compared to a more thorough check.

**Review by Jelly65 — APPROVED** [review]

File: src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs (hunk 1 above)
Comment (captainsafia) [reply src/Http/Http.Extensions/test/RequestDelegateGenerator/CompileTimeCreationTests.cs:146]: > Should there be test(s) for emitting source for valid endpoints when invalid endpoints are also used?

Good recommendation.

**Review by Jelly65 — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]

File: src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/DiagnosticEmitter.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (captainsafia) [reply src/Http/Http.Extensions/gen/StaticRouteHandlerModel/Emitters/DiagnosticEmitter.cs:19]: Have you used this in a generator? It seems like the API works by assessing accessibility within the context of an _existing_ syntax tree, but here we're trying to check accessibility in code we haven't generated yet.
