### ISSUE TITLE
Building the managed part without node installed doesn't work anymore

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/aspnetcore#59114]
Potentially regressed with https://github.com/dotnet/aspnetcore/pull/58721

```
    C:\git\dotnet\src\aspnetcore\src\Assets\Microsoft.AspNetCore.App.Internal.Assets.csproj(46,5): error : 'C:\git\dotnet\src\aspnetcore\src\Components\Web.JS\dist\Rel
  ease\blazor.web.js' does not exist. Run 'npm run build' in the repo root to generate the file.
    C:\git\dotnet\src\aspnetcore\src\Components\WebView\WebView\src\Microsoft.AspNetCore.Components.WebView.csproj(68,5): error : '..\..\..\Web.JS\dist\Release\blazor.
  webview.js' does not exist. Falling back to checked-in copy.
    CSC : error CS1566: Error reading resource '_framework/blazor.webview.js' -- 'Could not find a part of the path 'C:\git\dotnet\src\aspnetcore\src\Components\Web.JS
  \dist\Release\blazor.webview.js'.' [C:\git\dotnet\src\aspnetcore\src\Components\WebView\WebView\src\Microsoft.AspNetCore.Components.WebView.csproj]
```

Also note that this logic doesn't work anymore: https://github.com/dotnet/aspnetcore/blob/3ba179ad088127e35a2a3e4ca8bc24bfc099fef2/src/Components/WebView/WebView/src/Microsoft.AspNetCore.Components.WebView.csproj#L68

CI triggers a dev workflow job that validates certain dev scenario but building the managed part with `--no-build-nodejs` unfortunately isn't validated.

cc @MackinnonBuck
