### ISSUE TITLE
cannot convert type string to type dynamic

### ISSUE THREAD

**Issue by pabloFuenzalida** [dotnet/aspnetcore#42231]
### Description
*I manually translated these lines from spanish, sorry if they look odd*

...dev\ioserver\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Reports_DeviceGroupReport_razor.g.cs(468,145): error CS0400: The type or namespace 'dynamic' does not exist in the namespace global (are you missing an assembly reference?) [...dev\ioserver\AdminDashboard.Server.csproj]

...dev\ioserver\Pages\Reports\DeviceGroupReport.razor(137,72): error CS1503: Argument 1: can't cast 'string' to 'dynamic' [...dev\io\ioserver\AdminDashboard.Server.csproj]

### Configuration

* Which version of .NET is the code running on? 
7.0.100-preview.4.22252.9
* What OS and version, and for Linux, what distro? 
Win 10 pro
* What is the architecture (x64, x86, ARM, ARM64)? 
x64
* Do you know whether it is specific to that configuration? 
no
* If you're using Blazor, which web browser(s) do you see this issue in? 
compile time

### Regression?
this works on 6.0.300

### Other information
the dynamic parameter I assign to is a blazor component's parameter

**Comment by javiercn** [comment]
@pabloFuenzalida thanks for contacting us.

Can you create a minimal repro project that ilustrates the issue? Otherwise, its impossible for us to determine what is going on.
