### ISSUE TITLE
CA1825 error when building in source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/aspnetcore#43461]
aspnetcore fails to build in the latest 7.0.1xx-rc1 source-build with the following errors.  This is likely caused from source-build building with the latest compiler and roslyn-analyzers.  To unblock source-build a source-build patch was added to nowarn on CA1825.

```
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Framework/AspNetCoreAnalyzers/src/Analyzers/WebApplicationBuilder/WebApplicationBuilderAnalyzer.cs(16,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Framework/AspNetCoreAnalyzers/src/Analyzers/Microsoft.AspNetCore.App.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteHandlers/RouteHandlerAnalyzer.cs(14,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Framework/AspNetCoreAnalyzers/src/Analyzers/Microsoft.AspNetCore.App.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Framework/AspNetCoreAnalyzers/src/Analyzers/RenderTreeBuilder/RenderTreeBuilderAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Framework/AspNetCoreAnalyzers/src/Analyzers/Microsoft.AspNetCore.App.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/ComponentParameterAnalyzer.cs(19,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/ComponentParametersShouldBePublicCodeFixProvider.cs(17,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/ComponentParameterUsageAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/ComponentInternalUsageDiagnosticAnalzyer.cs(16,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Components/Analyzers/src/Microsoft.AspNetCore.Components.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/ComponentParameterAnalyzer.cs(14,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/Microsoft.AspNetCore.Components.SdkAnalyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/ComponentParametersShouldBePublicCodeFixProvider.cs(17,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/Microsoft.AspNetCore.Components.SdkAnalyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/ComponentParameterUsageAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/Microsoft.AspNetCore.Components.SdkAnalyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/ComponentInternalUsageDiagnosticAnalzyer.cs(16,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Tools/SDK-Analyzers/Components/src/Microsoft.AspNetCore.Components.SdkAnalyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/AvoidHtmlPartialAnalyzer.cs(11,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/Microsoft.AspNetCore.Mvc.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/TopLevelParameterNameAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/Microsoft.AspNetCore.Mvc.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/AttributesShouldNotBeAppliedToPageModelAnalyzer.cs(10,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/Microsoft.AspNetCore.Mvc.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/TagHelpersInCodeBlocksAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Analyzers/src/Microsoft.AspNetCore.Mvc.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/AddResponseTypeAttributeCodeFixProvider.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzer.cs(13,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/ApiConventionAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/ApiActionsDoNotRequireExplicitModelValidationCodeFixProvider.cs(16,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Mvc/Mvc.Api.Analyzers/src/Microsoft.AspNetCore.Mvc.Api.Analyzers.csproj]
  /repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Analyzers/Analyzers/src/StartupAnalyzer.cs(12,2): error CA1825: Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead. [/repos/tarball-rc1/src/aspnetcore/artifacts/source-build/self/src/src/Analyzers/Analyzers/src/Microsoft.AspNetCore.Analyzers.csproj]
```

**Comment by mkArtakMSFT** [comment]
This was due to a dependency flow / timing issue. It's fixed now, so closing.
