### PR TITLE
Update SDK to 23523.1

### PR DESCRIPTION
**Pull request by amcasey**
Regular BuildOps update

### CODE REVIEW

**Comment by wtgodbe** [comment]
This failure is the one where multiple tools in a `dotnet-tools.json` file causes a concurrent access issue - was fixed in 8.0 by https://github.com/dotnet/sdk/pull/35884. @JL03-Yue has that fix been ported to main yet?

**Comment by amcasey** [comment]
@wtgodbe It [looks](https://github.com/dotnet/sdk/blob/42305354de2a4686aa78685693eafd43f38a0d59/src/Cli/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs#L95) like it [has](https://github.com/dotnet/sdk/pull/36078).

**Comment by wtgodbe** [comment]
SDK -> Installer had been blocked for a really long time & only just got unblocked yesterday - I'm gonna try bumping this to the latest

**Comment by amcasey** [comment]
> SDK -> Installer had been blocked for a really long time & only just got unblocked yesterday - I'm gonna try bumping this to the latest

It no longer compiles 😆

**Comment by amcasey** [comment]
Looks like maybe a trimmer annotation changed?
```
src\JSInterop\Microsoft.JSInterop\src\Infrastructure\DotNetDispatcher.cs(391,67): error IL2111: Method 'ScanTypeForCallableMethods(Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [src\JSInterop\Microsoft.JSInterop\src\Microsoft.JSInterop.csproj]
```

**Comment by wtgodbe** [comment]
@eerhardt do you know anything about the trimming issue Andrew mentioned above?

**Comment by amcasey** [comment]
I haven't worked on trimmer warnings in a while, but the error seems superficially reasonable: we're operating on the type of a value of type `object` and we're enumerating its methods.  It's not immediately obvious how the trimmer could know to preserve the methods of that type.

**Comment by amcasey** [comment]
This looks like the original trimmer clean-up pass: #41610

**Comment by amcasey** [comment]
Suppressing with an attribute works, but I wasn't sure what justification to give (and the XML file doesn't contain one?).  @eerhardt?  Or @JamesNK?

```csharp
[UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Already suppressed in Microsoft.JSInterop.WarningSuppressions.xml, but that stopped working in https://github.com/dotnet/aspnetcore/pull/51588.")]
```

**Comment by eerhardt** [comment]
We shouldn't be suppressing this. This might be a bug in the latest ILLink analyzer (quite possibly from https://github.com/dotnet/runtime/pull/92724 ?).

@sbomer - can you take a look? Just pull this PR and `.\eng\build.cmd` from the root of the repo. You should see:

```
C:\git\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Infrastructure\DotNetDispatcher.cs(391,67): error IL2111: Method 'ScanTypeForCallableMethods(
Type)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of
 the requirements of the method. [C:\git\aspnetcore\src\JSInterop\Microsoft.JSInterop\src\Microsoft.JSInterop.csproj]
```

Note that this method is a local / nested method, so I'm not sure how it could be "accessed via reflection".

https://github.com/dotnet/aspnetcore/blob/82ff9246592477abf4ff57ac905a368cbd99ff20/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs#L388-L405

BTW - @amcasey, there are other build errors in this PR:

```
C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\src\HubConnection.cs(866,47): error CA2007: Consider calling ConfigureAwait on the awaited t
ask (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2007) [C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\sr
c\Microsoft.AspNetCore.SignalR.Client.Core.csproj::TargetFramework=net9.0]
C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\src\HubConnection.cs(866,47): error CA2007: Consider calling ConfigureAwait on the awaited t
ask (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2007) [C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\sr
c\Microsoft.AspNetCore.SignalR.Client.Core.csproj::TargetFramework=netstandard2.0]
C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\src\HubConnection.cs(866,47): error CA2007: Consider calling ConfigureAwait on the awaited t
ask (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2007) [C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\sr
c\Microsoft.AspNetCore.SignalR.Client.Core.csproj::TargetFramework=netstandard2.1]
C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\src\HubConnection.cs(866,47): error CA2007: Consider calling ConfigureAwait on the awaited t
ask (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2007) [C:\git\aspnetcore\src\SignalR\clients\csharp\Client.Core\sr
c\Microsoft.AspNetCore.SignalR.Client.Core.csproj::TargetFramework=net462]
```

**Comment by eerhardt** [comment]
Ah, I looked some more, and this is basically https://github.com/dotnet/linker/issues/2790, but now it is also in the ILLink Roslyn Analyzer, and not just in illink.exe.

It looks like we did suppress this warning in the Microsoft.JSInterop.WarningSuppressions.xml file, but the ILLink Roslyn Analyzer doesn't respect/know about that. Also the warnings coming from the 2 tools are different when analyzing this code. The warning from the ILLink Roslyn Analyzer is warning about the local function. The warning from illink.exe appears to be coming from the outer function.

So maybe a `#pragma warning disable` is appropriate here?

cc @vitek-karas @agocke @MichalStrehovsky

**Comment by amcasey** [comment]
FYI @BrennanConroy for the [SignalR errors](https://github.com/dotnet/aspnetcore/pull/51588#issuecomment-1779368952).

**Comment by BrennanConroy** [comment]
Just add `.ConfigureAwait(false)` on line 866 of HubConnection.

**Comment by JamesNK** [comment]
> So maybe a `#pragma warning disable` is appropriate here?

Replace XML suppression with pragma: [`533a66c` (#51588)](https://github.com/dotnet/aspnetcore/pull/51588/commits/533a66cfce8103d0b35d3769e1e67234a900bc85)

**Review by JamesNK — APPROVED** [review]
