### ISSUE TITLE
ViewComponents called with the vc taghelper are broken on 7.0.3

### ISSUE THREAD

**Issue by kanadaj** [dotnet/aspnetcore#46660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

View Components aren't called properly when building the project with .NET SDK 7.0.200. The tags are instead left on the page as a regular HTML tag. In some cases, passing arguments to the HTML tag results in `error CS1503: Argument 3: cannot convert from 'method group' to 'object?'`

This is likely a result of the newest SDK using `MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET`. I'm not sure a preview version of MSBuild was meant to leak into the production CLI.

Do not that I didn't update MSBuild separately, this is just what came with the 7.0.200 SDK.

### Expected Behavior

View Components should work

### Steps To Reproduce

Take any simple view component test repo, build and run it using MSBuild 17.5.0-preview-23061-01+040e2a90e

### .NET Version

7.0.200

### Anything else?

Using `dotnet publish`; this issue started surfacing on our build server. Using ASP.NET Core 7.0.2, but updating to 7.0.3 didn't seem to fix the issue.

```
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.200/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.416 [/usr/share/dotnet/sdk]
  5.0.404 [/usr/share/dotnet/sdk]
  6.0.300 [/usr/share/dotnet/sdk]
  7.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download```

**Comment by kanadaj** [comment]
Update: rolling back the SDK on the build agent to 7.0.103 fixes this issue. 7.0.200 seems broken w/r to ViewComponents due to the preview MSBuild version.
