### ISSUE TITLE
Microsoft.AspNetCore.Builder.IISServerOptions Class not existing in 9.0.103 (Linux)

### ISSUE THREAD

**Issue by jsnet-io** [dotnet/aspnetcore#60892]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Not much to describe any further.
When using SDK 9.0.103 (linux), the IISServerOptions Class is not found. When upgrading to 9.0.200-preview, it's back again.

**Comment by Zunair** [comment]
same issue on 9.0.105
`error CS0246: The type or namespace name 'IISServerOptions' could not be found (are you missing a using directive or an assembly reference?
`
App builds witout issues in windows.

**Comment by TariqHajeer** [comment]
@danmoseley 
are you going to solve it ?

**Comment by stephannn** [comment]
I solved it by wrapping it around an if:

```
#if WINDOWS
builder.Services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
#endif
```
