### ISSUE TITLE
Runtime Exception (Garbage collector could not allocate 16384 bytes) in Blazor client-side since 3.2

### ISSUE THREAD

**Issue by GillCleeren** [dotnet/aspnetcore#18659]
### Describe the bug
Exception is thrown when registering types with AutoMapper at runtime. 

### To Reproduce

In Program.cs:

`var builder = WebAssemblyHostBuilder.CreateDefault(args);

            var automapperConfig = new MapperConfiguration(configuration =>
            {
                configuration.AddProfile(new CustomMappings());
            });

            var autoMapper = automapperConfig.CreateMapper();

            builder.Services.AddSingleton(autoMapper);`

CustomMapping.cs contains (quite a few) mappings:
`public class CustomMappings : MapperConfigurationExpression
    {
        public CustomMappings()
        {
            CreateMap<WitnessDto, WitnessGeneralInfoViewModel>();
            CreateMap<WitnessGeneralInfoViewModel, WitnessDto >();`

The error is only happening when I create a large(r) number of mappings with their reverse (more than 15). Same happens with using ReverseMap.

The memory use of Chrome running this goes up over 2.1GB whereas the 3.1 version is around 150MB.

When running this code in 3.2 (update of Jan 28), I get the error below. The exact same code works in 3.1.

Here's the browser console output.
blazor.webassembly.js:1 WASM: Error: Garbage collector could not allocate 16384 bytes of memory for major heap section.
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: [object Object]
l.printErr @ blazor.webassembly.js:1
dotnet.js:1 Stacktrace: 

dotnet.js:1 Error
    at 650764 (dotnet.js:1)
    at _emscripten_asm_const_iii (dotnet.js:1)
    at :5001/wasm-function[3493]:0xab8a1
    at :5001/wasm-function[3796]:0xb9f77
    at :5001/wasm-function[3661]:0xb4e6d
    at :5001/wasm-function[2136]:0x65002
    at :5001/wasm-function[150]:0x3a1c
    at :5001/wasm-function[3892]:0xbe69e
    at :5001/wasm-function[3894]:0xbe87f
    at :5001/wasm-function[1243]:0x38052
blazor.webassembly.js:1 WASM: * Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: undefined
blazor.webassembly.js:1 WASM: undefined
l.printErr @ blazor.webassembly.js:1
dotnet.js:1 Uncaught RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:5001/_framework/wasm/dotnet.js:1:16107)
    at _abort (https://localhost:5001/_framework/wasm/dotnet.js:1:117299)
    at wasm-function[3493]:0xab8ae
    at wasm-function[3796]:0xb9f77
    at wasm-function[3661]:0xb4e6d
    at wasm-function[2136]:0x65002
    at wasm-function[150]:0x3a1c
    at wasm-function[3892]:0xbe69e
    at wasm-function[3894]:0xbe87f
    at wasm-function[1243]:0x38052
### Further technical details
- Blazor 3.2 Preview 1

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18617
