### ISSUE TITLE
QuickGrid with Virtualize=true - Samples Question

### ISSUE THREAD

**Issue by KurinchiA** [dotnet/aspnetcore#54034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to get the quick grid sample for Remote data provided in https://aspnet.github.io/quickgridsamples/datasources
to work in my local.

Created blazor webassembly project and added the code provided with the css. While compile getting error : 

1>C:\Users\arumugamk\source\repos\QuickGridTestApp\QuickGridTestApp\Components\Pages\VirtualizeAPIData.razor(19,23,19,33): error CS0246: The type or namespace name 'FoodRecall' could not be found (are you missing a using directive or an assembly reference?)

Where can i find the FoodRecall class?

----------------------------------
Same with https://aspnet.github.io/quickgridsamples/virtualizing
where can i find the DrugInfo class? and the DataSource injected.

My goal is to get a virtualization sample working in my local environment

### Expected Behavior

Expected to get the  sample provided in Remote data section of https://aspnet.github.io/quickgridsamples/datasources

and 
the code in sample for virtualizing - https://aspnet.github.io/quickgridsamples/virtualizing

to work independently in my local environment. 

This will help me to change the data to our data and trouble shot my issue. As when I use quickgrid with my data i don't see the data displayed in the grid but the count looks correct. which i already reported and trying to trouble shoot this issue by getting the sample working. 

### Steps To Reproduce

Created blazor webassembly project using visual studio.
Add a blazor page 
Copy the code from Remote data section of https://aspnet.github.io/quickgridsamples/datasources 
create a razor.css file with the same name as the razor page and copy the css from remote data section of https://aspnet.github.io/quickgridsamples/datasources 
Build the project.

### .NET Version

8.0.2

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/59615039/e6c23499-b349-46e8-9db3-8aef063805dc)

**Comment by mkArtakMSFT** [comment]
Here is the repo that houses the code for the quickgrid samples: https://github.com/aspnet/quickgridsamples
And here is the class that you're looking for: https://github.com/aspnet/quickgridsamples/blob/5056ca6a85d268cb5b3cba4de2126f1028ffcd40/src/QuickGridDemos/SampleData/FoodRecall.cs#L6

**Comment by KurinchiA** [comment]
sorry. the git urls you have provided are not working. Can you please double check the url and share. Thanks

![image](https://github.com/dotnet/aspnetcore/assets/59615039/2c0a2f75-3602-47a1-8b64-9860100f463d)

![image](https://github.com/dotnet/aspnetcore/assets/59615039/e53316a4-0490-46cf-9076-ae3e57d1f385)

**Comment by KurinchiA** [comment]
I don't have access to https://github.com/aspnet/quickgridsamples , can you please please provide access. Thanks.

**Comment by ricardowolff** [comment]
+1  I'm also interested in those source codes.

**Comment by dutompson** [comment]
I'm looking for those code samples too, particularly on how the EF context is set in Program.cs, lifetime type and if there's a need for factory.

**Comment by nikolareljin** [comment]
+1 I would also be interested in having the full code examples available. 
Microsoft usually does this very good. It would be very useful to have the full code samples for this, too.

Thanks!

**Comment by jrb-github** [comment]
See also [this related issue](https://github.com/dotnet/aspnetcore/issues/47261).
